# Generated by Django 3.2.5 on 2021-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprapp', '0002_table2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table2',
        ),
        migrations.AddField(
            model_name='table',
            name='email',
            field=models.CharField(default='Nadeem', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(),
        ),
    ]
